name: BlackBE
main: LixWorthWeida\BlackBE
version: 1.0
api: 3.0.0

load: POSTWORLD
author: LixWorth
description: BlackBE NK Plugin blacbe.xyz
website: https://github.com/lixworth/BlackBE-NKPlugin

commands:
 blackbe:
  description: BlackBE 云黑插件
  usage: "/blackbe"
